spring.application.name=Pravin
# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=health,info,metrics
# =========================
# H2DB
# =========================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# =========================
# Configure Hibernate DDL generation
# =========================

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true


# =========================
# API DOC
# =========================

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.writer-with-default-pretty-printer=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
spring.main.allow-bean-definition-overriding=true
spring.mvc.problemdetails.enabled=true

# =========================
# API VERSION - NEW FEATURES
# =========================
spring.mvc.apiversion.enabled=true
spring.mvc.apiversion.use.header=API-Version
# Define which versions are available
spring.mvc.apiversion.supported=1, 2
# Set a fallback version
spring.mvc.apiversion.default=1
spring.threads.virtual.enabled=true
#management.otlp.tracing.endpoint=http://localhost:4318